name: 'SAFE Testnet deployer'
description: 'GitHub action to deploy a testnet using Digital Ocean droplets'
inputs:
  do-token:
    description: 'Digital Ocean Authorization token'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-access-key-secret:
    description: 'AWS Access Key'
    required: true
  aws-default-region:
    description: 'AWS Default region'
    default: eu-west-2
  ssh-secret-key:
    description: 'SSH key used to run the nodes on the Digital Ocean droplets'
    required: true
  node-count:
    description: 'Number of nodes to be deployed'
    default: 50
  node-path:
    description: 'Path to the node binary'
    default: "\"\""
  node-version:
    description: 'Node version'
    default: "\"\""
  action:
    description: "Task to be carried out. Accepts 'create' or 'destroy'"
    default: 'create'

runs:
  using: "composite"
  steps:
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
    - name: Set TESTNET_ID env
      shell: bash
      run: echo "TESTNET_ID=gha-testnet-$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    - name: Deploy Testnet
      env:
        DO_PAT: ${{ inputs.do-token }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-access-key-secret }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-default-region }}
      shell: bash
      run: |
        if [[ "${{inputs.action}}" == "create" ]]; then
          git clone https://github.com/lionel1704/sn_testnet_tool ${{ github.action_path }}/sn_testnet_tool --depth 1
          cd ${{ github.action_path }}/sn_testnet_tool
          terraform init
          terraform workspace select ${{ env.TESTNET_ID }} || terraform workspace new ${{ env.TESTNET_ID }}
          echo "${{ inputs.ssh-secret-key }}" > ${{ github.action_path }}/id_rsa
          chmod 600 ${{ github.action_path }}/id_rsa
          eval `ssh-agent`
          ssh-add ${{ github.action_path }}/id_rsa
          ${{ github.action_path }}/sn_testnet_tool/up.sh ${{ github.action_path }}/id_rsa ${{ inputs.node-count }} ${{ inputs.node-path }} ${{ inputs.node-version }} "-auto-approve" \
          || ${{ github.action_path }}/sn_testnet_tool/down.sh ${{ github.action_path }}/id_rsa
        fi
    - uses: actions/upload-artifact@v2
      with:
        name: node_connection_info.config
        path: ${{ github.action_path }}/${{ env.TESTNET_ID }}-node_connection_info.config
    - name: Destroy Testnet
      env:
        DO_PAT: ${{ inputs.do-token }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-access-key-secret }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-default-region }}
      shell: bash
      run: |
        if [[ "${{inputs.action}}" == "destroy" ]]; then
          git clone https://github.com/lionel1704/sn_testnet_tool ${{ github.action_path }}/sn_testnet_tool --depth 1
          cd ${{ github.action_path }}/sn_testnet_tool
          terraform init
          terraform workspace select ${{ env.TESTNET_ID }} || terraform workspace new ${{ env.TESTNET_ID }}
          ${{ github.action_path }}/sn_testnet_tool/down.sh dummy-arg "-auto-approve"
        fi